// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	FirstName    pgtype.Text        `json:"first_name"`
	ProfileImage pgtype.Text        `json:"profile_image"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
