services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=heyanantraj@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.http.middlewares.test-ratelimit.ratelimit.average=100"
      - "traefik.http.middlewares.test-ratelimit.ratelimit.burst=200"
      - "traefik.http.middlewares.test-compress.compress=true"
      - "traefik.http.middlewares.test-compress.compress.defaultEncoding=gzip"
      - "traefik.http.middlewares.test-compress.compress.encodings=gzip,zstd,br"
      - "traefik.http.middlewares.test-retry.retry.attempts=4"
      - "traefik.http.middlewares.test-retry.retry.initialinterval=100ms"
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - CF_DNS_API_TOKEN
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/CF_DNS_API_TOKEN
    volumes:
      - letsencrypt:/letsencrypt
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  greed:
    image: ghcr.io/greed-verse/greed-backend:${GIT_COMMIT_HASH:-latest}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.greed.rule=Host(`greed.tutorme.tech`)"
      - "traefik.http.routers.greed.entrypoints=websecure"
      - "traefik.http.routers.greed.tls.certresolver=myresolver"
      - "traefik.http.services.greed.loadbalancer.server.port=3000"
    deploy:
      mode: replicated
      replicas: 3
    secrets:
      - APP_ADDRESS
      - STRIPE_KEY
      - DB_URL
    environment:
      - APP_ADDRESS_FILE=/run/secrets/APP_ADDRESS
      - STRIPE_KEY_FILE=/run/secrets/STRIPE_KEY
      - DB_URL_FILE=/run/secrets/DB_URL
volumes:
  letsencrypt:

secrets:
  CF_DNS_API_TOKEN:
    external: true
  APP_ADDRESS:
    external: true
  STRIPE_KEY:
    external: true
  DB_URL:
    external: true
